services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:80
    extends:
      file: common-config.yml
      service: network-deploy-service

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    extends:
      file: common-config.yml
      service: network-deploy-service

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: view-service
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    extends:
      file: common-config.yml
      service: network-deploy-service

  s3:
    image: minio/minio
    container_name: s3
    environment:
      MINIO_ACCESS_KEY: user
      MINIO_SECRET_KEY: password
    command: server /data
    ports:
      - "9001:9000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  recommends:
    image: "vibecast/recommend-service"
    container_name: recommends-ms
    ports:
      - 8082:8082
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  views:
    image: "vibecast/view-service"
    container_name: views-ms
    ports:
      - 8080:8080
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: password
      SPRING_DATA_MONGODB_DATABASE: view-service
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      S3_ENDPOINT_URL: http://s3:9000
    extends:
      file: common-config.yml
      service: microservice-base-config
    depends_on:
      redis:
        condition: service_healthy
      s3:
        condition: service_healthy
      mongodb:
        condition: service_started

  streams:
    image: "vibecast/stream-service"
    container_name: streams-ms
    ports:
      - 8081:8081
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      S3_ENDPOINT_URL: http://s3:9000
    extends:
      file: common-config.yml
      service: microservice-base-config
    depends_on:
      redis:
        condition: service_healthy
      s3:
        condition: service_healthy

networks:
  vibecast:
    driver: "bridge"
