spring:
  application:
    name: streams
  cache:
      type: redis
  data:
    redis:
      host: localhost
      port: 6379


server:
  port: 8081

s3:
  bucket:
    name: vibecast
  access:
    key: user
  secret:
    key: password
  endpoint:
    url: http://localhost:9000
  region: us-east-1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "streams"
    description: "Vibecast Stream Application"
    version: "1.0.0"