spring:
  application:
    name: views

  data:
    mongodb:
      auto-index-creation: true
      username: root
      password: password
      database: view-service
      host: localhost
      authentication-database: admin
      port: 27017
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  servlet:
    multipart:
      max-file-size: 10MB

s3:
  bucket:
    name: vibecast
  access:
    key: user
  secret:
    key: password
  endpoint:
    url: http://localhost:9000
  region: us-east-1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "views"
    description: "Vibecast Metadata Application"
    version: "1.0.0"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG