spring:
  data:
    mongodb:
      auto-index-creation: true
      username: root
      password: password
      database: view-service
      host: localhost
      authentication-database: admin
      port: 27017
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG